services:
  postgres:
    image: "postgres:15"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: crate_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
volumes:
  pgdata:
